package com.aemm.libreria.util

enum class EnumFirebaseCode(code: String) {
    ERROR_INVALID_EMAIL("ERROR_INVALID_EMAIL"),
    ERROR_WRONG_PASSWORD("ERROR_WRONG_PASSWORD"),
    ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL("ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL"),
    ERROR_EMAIL_ALREADY_IN_USE("ERROR_EMAIL_ALREADY_IN_USE"),
    ERROR_USER_TOKEN_EXPIRED("ERROR_USER_TOKEN_EXPIRED"),
    ERROR_USER_NOT_FOUND("ERROR_USER_NOT_FOUND"),
    ERROR_WEAK_PASSWORD("ERROR_WEAK_PASSWORD"),
    NO_NETWORK("NO_NETWORK")
}
